
services:
  mongo:
    image: mongo:6.0
    container_name: nonagon-mongo
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: nonagon-api
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/?authSource=admin
      DB_NAME: nonagon
    depends_on:
      mongo: { condition: service_healthy }
    ports: ["8000:8000"]
    volumes:
      - ./src:/app/src
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: nonagon-bot
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/?authSource=admin
      DB_NAME: nonagon
      DISCORD_TOKEN: ${DISCORD_TOKEN:-replace_me_in_.env}
    depends_on:
      mongo: { condition: service_healthy }
    volumes:
      - ./src:/app/src
    # no ports; it's a worker
