services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: nonagon-api
    environment:
      MONGODB_URI: ${ATLAS_URI:?Set ATLAS_URI in .env to your MongoDB Atlas connection string}
      DB_NAME: ${DB_NAME:-nonagon}
    ports: ["8000:8000"]
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: nonagon-bot
    environment:
      MONGO_URI: ${ATLAS_URI:?Set ATLAS_URI in .env to your MongoDB Atlas connection string}
      DB_NAME: ${DB_NAME:-nonagon}
      BOT_TOKEN: ${BOT_TOKEN:-replace_me_in_.env}
      BOT_CLIENT_ID: ${BOT_CLIENT_ID:-}
      DEMO_RESET_ENABLED: ${DEMO_RESET_ENABLED:-false}
      DEMO_LOG_CHANNEL_ID: ${DEMO_LOG_CHANNEL_ID:-}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
