services:

  bot:
    container_name: bot
    build:
      dockerfile: Dockerfile.bot
    env_file: .env
    volumes:
      - ./:/nonagon
      - ./logs:/nonagon/logs

  api:
    container_name: api
    build:
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/nonagon
      - ./logs:/nonagon/logs
