name: nonagon
services:
  - name: api
    source_dir: .
    dockerfile_path: Dockerfile.api
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: MONGODB_URI
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: DB_NAME
        scope: RUN_AND_BUILD_TIME
        value: "nonagon"
routes:
  - path: /
    preserve_path_prefix: false
    service: api
  - name: bot
    source_dir: .
    dockerfile_path: Dockerfile.bot
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: MONGO_URI
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: DB_NAME
        scope: RUN_AND_BUILD_TIME
        value: "nonagon"
      - key: BOT_TOKEN
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: BOT_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        value: ""
      - key: DEMO_RESET_ENABLED
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: DEMO_LOG_CHANNEL_ID
        scope: RUN_AND_BUILD_TIME
        value: ""
